import { NextRequest, NextResponse } from 'next/server';
import { parseSocialExport } from '@/lib/parsers';
import { LocalVectorStore, VectorNode, PlatformProfile } from '@/lib/vectorStore';
import { RAGService } from '@/lib/services/rag';
import JSZip from 'jszip';

export const maxDuration = 300; // Allow long execution times for large zip processing

export async function POST(req: NextRequest) {
  try {
    const authHeader = req.headers.get('Authorization');
    const headerKey = authHeader ? authHeader.replace('Bearer ', '').trim() : '';
    const apiKey = headerKey || process.env.OPENAI_API_KEY;

    if (!apiKey) {
      return NextResponse.json(
        { error: 'API key is required. Please set it in the Settings panel.' },
        { status: 400 }
      );
    }

    // 2. Parse Form Data
    const formData = await req.formData();
    const uploadedFiles = formData.getAll('files') as File[];

    if (uploadedFiles.length === 0) {
      return NextResponse.json({ error: 'No files uploaded.' }, { status: 400 });
    }

    const filesMap: Record<string, string> = {};

    // 3. Process Files (unzip if necessary, read content as text)
    for (const file of uploadedFiles) {
      const isZip = file.name.endsWith('.zip') || file.type === 'application/zip' || file.type === 'application/x-zip-compressed';
      
      if (isZip) {
        const buffer = await file.arrayBuffer();
        const zip = await JSZip.loadAsync(buffer);
        
        for (const [relativePath, zipEntry] of Object.entries(zip.files)) {
          if (!zipEntry.dir) {
            // Read text files only for parser ingestion (CSV, JSON, JS, HTML)
            const ext = relativePath.split('.').pop()?.toLowerCase();
            if (ext && ['csv', 'json', 'js', 'html', 'txt'].includes(ext)) {
              const textContent = await zipEntry.async('string');
              filesMap[relativePath] = textContent;
            }
          }
        }
      } else {
        // Individual file upload
        const textContent = await file.text();
        filesMap[file.name] = textContent;
      }
    }

    if (Object.keys(filesMap).length === 0) {
      return NextResponse.json(
        { error: 'No readable text files found (CSV, JSON, JS, HTML).' },
        { status: 400 }
      );
    }

    // 4. Parse Social Media Content
    const parsed = parseSocialExport(filesMap);
    const store = new LocalVectorStore();

    // 5. Save/Register profile if present
    const profileName = parsed.profile?.name || `${parsed.platform.toUpperCase()} User`;
    if (parsed.profile) {
      store.addProfile(parsed.platform, parsed.profile);
    } else {
      // Create a default profile if not present
      const defaultProfile: PlatformProfile = {
        name: profileName,
        username: `${parsed.platform}_user`,
        bio: `Autogenerated profile for ingested ${parsed.platform} data.`,
      };
      store.addProfile(parsed.platform, defaultProfile);
    }

    // 6. Deduplicate & Chunk Posts
    const newPostsToProcess = parsed.posts.filter(post => {
      const postHash = LocalVectorStore.computeHash(post.content + post.platform + post.timestamp);
      return !store.hasContent(postHash);
    });

    const duplicateCount = parsed.posts.length - newPostsToProcess.length;

    if (newPostsToProcess.length === 0) {
      return NextResponse.json({
        message: 'Ingestion complete.',
        platform: parsed.platform,
        totalParsed: parsed.posts.length,
        newIngested: 0,
        duplicatesSkipped: duplicateCount,
        stats: store.stats(),
      });
    }

    // Prepare chunks to embed
    const chunksToEmbed: Array<{
      postId: string;
      content: string;
      index: number;
      post: typeof newPostsToProcess[0];
    }> = [];

    newPostsToProcess.forEach(post => {
      const chunks = LocalVectorStore.chunkPost(post.content);
      chunks.forEach((chunkContent, idx) => {
        chunksToEmbed.push({
          postId: post.id,
          content: chunkContent,
          index: idx,
          post,
        });
      });
    });

    // 7. Get Embeddings (using batching to handle 10k+ chunks efficiently)
    const textsToEmbed = chunksToEmbed.map(c => c.content);
    const embeddings = await RAGService.getEmbeddingsBatch(textsToEmbed, apiKey);

    // 8. Map to VectorNodes
    const nodes: VectorNode[] = chunksToEmbed.map((item, idx) => {
      const postHash = LocalVectorStore.computeHash(item.post.content + item.post.platform + item.post.timestamp);
      return {
        id: `${item.postId}-${item.index}`,
        postId: item.postId,
        platform: item.post.platform,
        content: item.content,
        timestamp: item.post.timestamp,
        url: item.post.url,
        media: item.post.media,
        author: profileName,
        hash: postHash,
        embedding: embeddings[idx],
      };
    });

    // 9. Save to local vector db
    store.upsertNodes(nodes);

    return NextResponse.json({
      message: 'Ingestion complete.',
      platform: parsed.platform,
      totalParsed: parsed.posts.length,
      newIngested: newPostsToProcess.length,
      chunksCreated: nodes.length,
      duplicatesSkipped: duplicateCount,
      stats: store.stats(),
    });
  } catch (err) {
    console.error('Ingestion error:', err);
    return NextResponse.json(
      { error: (err as Error).message || 'An error occurred during ingestion.' },
      { status: 500 }
    );
  }
}
